### ISSUE TITLE
Cari Konten Buat Tampilan WEB

### ISSUE THREAD

**Issue by DoctorZeee** [DoctorZeee/projek-web-pemdas#17]
Kalian cari nih misal link link yang ada lowongan gitu gitunya sama mungkin ntar gambar gambar kalo dibutuhin

**Comment by nayaazcc** [comment]
dim ini nyari linknya tu yang langsung tertuju ama lowongannya atau nyarii yang link di dalemnya ada beberapa lowongan, misal kaya link langsung jadi kasir atau link di resto yang lowonganya ada kasir ada OB ada koki gitu?

**Comment by nayaazcc** [comment]
[link loker.xlsx](https://github.com/user-attachments/files/17840428/link.loker.xlsx)

**Comment by DoctorZeee** [comment]
Gess sama cariin deskripsinya dong
